Spark.Templates/working/templates/Spark.Templates.Razor/Pages/Admin/Dashboard.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Spark.Templates.Razor.Application.Models;

namespace Spark.Templates.Razor.Pages.Admin
{
	[Authorize(Policy = CustomRoles.Admin)]
	public class DashboardModel : PageModel
	{
		public void OnGet()
		{
		}
	}
}

Spark.Templates/working/templates/Spark.Templates.Razor/Pages/Home/Dashboard.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Spark.Templates.Razor.Application.Models;

namespace Spark.Templates.Razor.Pages.Home
{
	[Authorize]
	public class DashboardModel : PageModel
	{
		public void OnGet()
		{
		}
	}
}

Spark.Templates/working/templates/Spark.Templates.Razor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Spark.Templates.Razor.Pages
{
	public class IndexModel : PageModel
	{
		public void OnGet()
		{
		}
	}
}

Spark.Templates/working/templates/Spark.Templates.Razor/Pages/Profile/Edit.cshtml.cs
using Coravel.Events.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Spark.Library.Extensions;
using Spark.Templates.Razor.Application.Database;
using Spark.Templates.Razor.Application.Services.Auth;
using Spark.Templates.Razor.Pages.Auth;
using System.ComponentModel.DataAnnotations;

namespace Spark.Templates.Razor.Pages.Profile
{
    [Authorize]
    public class EditModel : PageModel
    {
        private readonly UsersService _usersService;
        private readonly AuthService _authService;
        private readonly IConfiguration _configuration;
        private readonly DatabaseContext _db;
        private IDispatcher _dispatcher;

        [BindProperty]
        public ProfileInfoEditor ProfileInfo { set; get; } = new();

        [BindProperty]
        public ProfilePasswordEditor ProfilePassword { set; get; } = new();

        public EditModel(UsersService usersService, IConfiguration configuration, IDispatcher dispatcher, AuthService authService, DatabaseContext db)
        {
            _usersService = usersService;
            _configuration = configuration;
            _dispatcher = dispatcher;
            _authService = authService;
            _db = db;
        }

        public async Task OnGet()
        {
            var user = await _authService.GetAuthenticatedUser(User);
            ProfileInfo.Name = user.Name;
            ProfileInfo.Email = user.Email;
        }

        public async Task<IActionResult> OnPostUpdateInfo()
        {
            if (ModelState.GetFieldValidationState("ProfileInfo") != ModelValidationState.Valid)
            {
                return new PageResult();
            }

            var currentUser = await _authService.GetAuthenticatedUser(User);

            if (currentUser != null)
            {
                var existingUser = await _usersService.FindUserByEmailAsync(ProfileInfo.Email);

                if (existingUser != null && currentUser.Id != existingUser.Id)
                {
                    ModelState.AddModelError("ProfileInfo.Email", "Email already in use.");
                    return new PageResult();
                }

                currentUser.Email = ProfileInfo.Email;
                currentUser.Name = ProfileInfo.Name;

                _db.Users.Save(currentUser);

                await _authService.RefreshSignIn(currentUser);
            }
            return Redirect("/profile/edit");
        }

        public async Task<IActionResult> OnPostUpdatePassword()
        {
            if (ModelState.GetFieldValidationState("ProfilePassword") != ModelValidationState.Valid)
            {
                return new PageResult();
            }
            var user = await _authService.GetAuthenticatedUser(User);

            var existingUser = await _usersService.FindUserAsync(user.Email, _usersService.GetSha256Hash(ProfilePassword.CurrentPassword));

            if (existingUser == null)
            {
                ModelState.AddModelError("ProfilePassword.CurrentPassword", "Current password was incorrect.");
                return new PageResult();
            }

            existingUser.Password = _usersService.GetSha256Hash(ProfilePassword.NewPassword);

            _db.Users.Save(existingUser);
            return Redirect("/profile/edit");
        }
    }

    public class ProfileEditor
    {
        public ProfileInfoEditor ProfileInfoEditor { get; set; } = new();
        public ProfilePasswordEditor ProfilePasswordEditor { get; set; } = new();
    }

    public class ProfileInfoEditor
    {
        [Required]
        public string Name { get; set; }

        [EmailAddress(ErrorMessage = "Invalid email address.")]
        [Required(ErrorMessage = "Please enter a valid email address")]
        public string Email { get; set; }
    }

    public class ProfilePasswordEditor
    {
        [Required(ErrorMessage = "Current Password is required")]
        public string CurrentPassword { get; set; }

        [Required(ErrorMessage = "New Password is required")]
        public string NewPassword { get; set; }

        [Required(ErrorMessage = "Confirm password is required")]
        [Compare("NewPassword", ErrorMessage = "The New Password and Confirm Password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

Spark.Templates/working/templates/Spark.Templates.Razor/Pages/Admin/Dashboard.cshtml
@page "/admin/dashboard"
@model DashboardModel
@{
    ViewData["Title"] = "Admin dashboard";
}
﻿//#if (IsTailwind)
<section class="mx-auto max-w-6xl bg-white mb-20">
    <article class="my-6 sm:my-20 px-6 py-12 sm:py-20 sm:px-12 shadow-lg rounded-lg text-left">
        <h1 class="text-3xl sm:text-4xl font-bold text-gray-800 mb-20">
            Admin Dashboard
        </h1>
    </article>
</section>
//#endif
﻿//#if (IsPico)
<section>
    <article>
        <h1>
            Admin Dashboard
        </h1>
    </article>
</section>
//#endif
﻿//#if (IsBootstrap)
<section class="container py-5 my-5 text-left">
    <article class="p-5 my-5 shadow rounded text-left bg-white">
        <h1 class="mb-5 fw-bold">
            Admin Dashboard
        </h1>
    </article>
</section>
//#endif

Spark.Templates/working/templates/Spark.Templates.Razor/Pages/Home/Dashboard.cshtml
@page "/dashboard"
@model DashboardModel﻿
@{
    ViewData["Title"] = "Dashboard";
}﻿
//#if (IsTailwind)
<section class="mx-auto max-w-6xl mb-20">
    <h1 class="text-2xl text-gray-800 font-bold mb-4">
        Dashboard
    </h1>
    <article class="bg-white shadow rounded-lg w-full my-12 p-6">
        <p class="text-gray-600">
            You're logged in!
        </p>
    </article>
</section>
//#endif
﻿//#if (IsPico)
<section>
    <h1>
        Dashboard
    </h1>
    <article>
        <p>
            You're logged in!
        </p>
    </article>
</section>
//#endif
﻿//#if (IsBootstrap)
<section class="container py-5 my-5 text-left">
    <h1 class="mb-5 fw-bold">
        Dashboard
    </h1>
    <article class="p-5 my-5 shadow rounded text-left bg-white">
        <p>
            You're logged in!
        </p>
    </article>
</section>
//#endif

Spark.Templates/working/templates/Spark.Templates.Razor/Pages/Index.cshtml
@page "/"
@{
    ViewData["Title"] = "Home Page";
}
﻿//#if (IsTailwind)
<section class="mx-auto max-w-6xl bg-white mb-20">
    <article class="my-6 sm:my-20 px-6 py-12 sm:py-20 sm:px-12 shadow-lg rounded-lg text-left">
        <h1 class="text-3xl sm:text-4xl font-bold text-gray-800 mb-8 sm:mb-20">
            Build something beautiful
        </h1>
        <p class="text-base sm:text-xl text-gray-600 mb-6">
            Spark picks up where ASP.NET leaves off. Build production ready, full-stack web applications fast.
        </p>
        <p class="text-base sm:text-xl text-gray-600 mb-6">
            View the <a class="text-indigo-600 font-semibold hover:underline" href="https://spark-framework.net" target="_blank">documentation →</a>
        </p>
    </article>
</section>
//#endif
﻿//#if (IsPico)
<section>
    <article>
        <h1>
            Build something beautiful
        </h1>
        <p>
            Spark picks up where ASP.NET leaves off. Build production ready, full-stack web applications fast.
        </p>
        <p>
            View the <a href="https://spark-framework.net" target="_blank"><strong>documentation →</strong></a>
        </p>
    </article>
</section>
//#endif
﻿//#if (IsBootstrap)
<section class="container py-5 my-5 text-left">
    <article class="p-5 my-5 shadow rounded text-left bg-white">
        <h1 class="mb-5 fw-bold">
            Build something beautiful
        </h1>
        <p class="">
            Spark picks up where ASP.NET leaves off. Build production ready, full-stack web applications fast.
        </p>
        <p class="">
            View the <a class="link-primary" href="https://spark-framework.net" target="_blank">documentation →</a>
        </p>
    </article>
</section>
//#endif

Spark.Templates/working/templates/Spark.Templates.Razor/Pages/Profile/Edit.cshtml
@page "/profile/edit"
@model EditModel
@{
    ViewData["Title"] = "Edit Profile";
}

//#if (IsTailwind)
<section class="mx-auto max-w-6xl mb-20">
    <h1 class="text-2xl text-gray-800 font-bold mb-4">
        Profile
    </h1>
    <article class="bg-white shadow rounded-lg w-full my-12 p-6">
        <h2 class="text-xl font-medium mb-2">
            Profile Information
        </h2>
        <p class="text-gray-600">
            Update your account's profile information.
        </p>
        <form method="post" asp-page-handler="UpdateInfo" class="max-w-2xl flex flex-col space-y-6">
            <div class="mt-6">
                <label asp-for="@Model.ProfileInfo.Name" class="block font-medium text-sm text-gray-700">Name</label>
                <div class="mt-1">
                    <input asp-for="@Model.ProfileInfo.Name" required class="border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm block mt-1 w-full" />
                </div>
                <div class="mt-1 text-red-500 text-sm">
                    @Html.ValidationMessageFor(m => m.ProfileInfo.Name)
                </div>
            </div>
            <div>
                <label asp-for="@Model.ProfileInfo.Email" class="block font-medium text-sm text-gray-700">Email address</label>
                <div class="mt-1">
                    <input asp-for="@Model.ProfileInfo.Email" required type="email" class="border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm block mt-1 w-full" />
                </div>
                <div class="mt-1 text-red-500 text-sm">
                    @Html.ValidationMessageFor(m => m.ProfileInfo.Email)
                </div>
            </div>
            <div>
                <button type="submit" class="text-left px-4 py-2 bg-indigo-700 hover:bg-indigo-800 rounded-md font-semibold text-xs text-white uppercase tracking-widest focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition">
                    Save
                </button>
            </div>
        </form>
    </article>
    <article class="bg-white shadow rounded-lg w-full my-12 p-6">
        <h2 class="text-xl font-medium mb-2">
            Update Password
        </h2>
        <p class="text-gray-600">
            Update your accounts current password.
        </p>
        <form method="post" asp-page-handler="UpdatePassword" class="max-w-2xl flex flex-col space-y-6">
            <div class="mt-6">
                <label asp-for="@Model.ProfilePassword.CurrentPassword" class="block font-medium text-sm text-gray-700">Current Password</label>
                <div class="mt-1">
                    <input asp-for="@Model.ProfilePassword.CurrentPassword" type="password" required class="border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm block mt-1 w-full" />
                </div>
                <div class="mt-1 text-red-500 text-sm">
                    @Html.ValidationMessageFor(m => m.ProfilePassword.CurrentPassword)
                </div>
            </div>
            <div>
                <label asp-for="@Model.ProfilePassword.NewPassword" class="block font-medium text-sm text-gray-700">New Password</label>
                <div class="mt-1">
                    <input asp-for="@Model.ProfilePassword.NewPassword" type="password" required class="border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm block mt-1 w-full" />
                </div>
                <div class="mt-1 text-red-500 text-sm">
                    @Html.ValidationMessageFor(m => m.ProfilePassword.NewPassword)
                </div>
            </div>
            <div>
                <label asp-for="@Model.ProfilePassword.ConfirmPassword" class="block font-medium text-sm text-gray-700">Confirm Password</label>
                <div class="mt-1">
                    <input asp-for="@Model.ProfilePassword.ConfirmPassword" type="password" required class="border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm block mt-1 w-full" />
                </div>
                <div class="mt-1 text-red-500 text-sm">
                    @Html.ValidationMessageFor(m => m.ProfilePassword.ConfirmPassword)
                </div>
            </div>
            <div>
                <button type="submit" class="text-left px-4 py-2 bg-indigo-700 hover:bg-indigo-800 rounded-md font-semibold text-xs text-white uppercase tracking-widest focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition">
                    Save
                </button>
            </div>
        </form>
    </article>
</section>
//#endif
﻿//#if (IsPico)
<section>
    <h1>
        Profile
    </h1>
    <article>
        <h2>
            Profile Information
        </h2>
        <p>
            Update your account's profile information.
        </p>
        <form method="post" asp-page-handler="UpdateInfo">
            <div>
                <label asp-for="@Model.ProfileInfo.Name">Name</label>
                <input asp-for="@Model.ProfileInfo.Name" required />
                <small>
                    @Html.ValidationMessageFor(m => m.ProfileInfo.Name)
                </small>
            </div>
            <div>
                <label asp-for="@Model.ProfileInfo.Email">Email</label>
                <input asp-for="@Model.ProfileInfo.Email" type="email" required />
                <small>
                    @Html.ValidationMessageFor(m => m.ProfileInfo.Email)
                </small>
            </div>
            <div class="grid">
                <button type="submit">
                    Save
                </button>
            </div>
        </form>
    </article>
    <article>
        <h2>
            Update Password
        </h2>
        <p>
            Update your accounts current password.
        </p>
        <form method="post" asp-page-handler="UpdatePassword">
            <div>
                <label asp-for="@Model.ProfilePassword.CurrentPassword">Current Password</label>
                <input asp-for="@Model.ProfilePassword.CurrentPassword" type="password" required />
                <small>
                    @Html.ValidationMessageFor(m => m.ProfilePassword.CurrentPassword)
                </small>
            </div>
            <div>
                <label asp-for="@Model.ProfilePassword.NewPassword">New Password</label>
                <input asp-for="@Model.ProfilePassword.NewPassword" type="password" required />
                <small>
                    @Html.ValidationMessageFor(m => m.ProfilePassword.NewPassword)
                </small>
            </div>
            <div>
                <label asp-for="@Model.ProfilePassword.ConfirmPassword">Confirm Password</label>
                <input asp-for="@Model.ProfilePassword.ConfirmPassword" type="password" required />
                <small>
                    @Html.ValidationMessageFor(m => m.ProfilePassword.ConfirmPassword)
                </small>
            </div>
            <div class="grid">
                <button type="submit">
                    Save
                </button>
            </div>
        </form>
    </article>
</section>
//#endif
﻿//#if (IsBootstrap)
<section class="container py-5 my-5">
    <h1 class="mb-5 fw-bold">
        Profile
    </h1>
    <article class="p-5 my-5 shadow rounded bg-white">
        <h2>
            Profile Information
        </h2>
        <p>
            Update your account's profile information.
        </p>
        <form method="post" asp-page-handler="UpdateInfo">
            <div class="mb-3">
                <label asp-for="@Model.ProfileInfo.Name" class="form-label">Name</label>
                <input asp-for="@Model.ProfileInfo.Name" class="form-control" required />
                <small class="text-danger">
                    @Html.ValidationMessageFor(m => m.ProfileInfo.Name)
                </small>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ProfileInfo.Email" class="form-label">Email</label>
                <input asp-for="@Model.ProfileInfo.Email" type="email" class="form-control" required />
                <small class="text-danger">
                    @Html.ValidationMessageFor(m => m.ProfileInfo.Email)
                </small>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </article>
    <article class="p-5 my-5 shadow rounded bg-white">
        <h2>
            Update Password
        </h2>
        <p>
            Update your accounts current password.
        </p>
        <form method="post" asp-page-handler="UpdatePassword">
            <div class="mb-3">
                <label asp-for="@Model.ProfilePassword.CurrentPassword" class="form-label">Current Password</label>
                <input asp-for="@Model.ProfilePassword.CurrentPassword" type="password" required class="form-control" />
                <small class="text-danger">
                    @Html.ValidationMessageFor(m => m.ProfilePassword.CurrentPassword)
                </small>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ProfilePassword.NewPassword" class="form-label">New Password</label>
                <input asp-for="@Model.ProfilePassword.NewPassword" type="password" required class="form-control" />
                <small class="text-danger">
                    @Html.ValidationMessageFor(m => m.ProfilePassword.NewPassword)
                </small>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ProfilePassword.ConfirmPassword" class="form-label">Confirm Password</label>
                <input asp-for="@Model.ProfilePassword.ConfirmPassword" type="password" required class="form-control" />
                <small class="text-danger">
                    @Html.ValidationMessageFor(m => m.ProfilePassword.ConfirmPassword)
                </small>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </article>
</section>
//#endif

Spark.Templates/working/templates/Spark.Templates.Razor/Pages/Shared/_ApplicationLogo.cshtml
﻿//#if (IsTailwind)
<div class="inline-flex items-center">
	<img src="~/images/logo.png" class="h-8 w-auto mr-2" />
	<h4 class="text-2xl font-bold text-gray-700">@Env.Get("APP_NAME")</h4>
</div>
//#endif
﻿//#if (IsPico)
<div style="display: inline-flex; align-items: center;">
	<img src="~/images/logo.png" width="25" height="auto" />
	<h4 style="margin-bottom: 0; margin-left: 5px;">@Env.Get("APP_NAME")</h4>
</div>
//#endif
﻿//#if (IsBootstrap)
<div class="d-inline-flex align-items-center">
	<img src="~/images/logo.png" width="25" height="auto" />
	<h4 class="fw-bold text-secondary-emphasis ms-2">@Env.Get("APP_NAME")</h4>
</div>
//#endif

Spark.Templates/working/templates/Spark.Templates.Razor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    ﻿//#if (IsTailwind)
    <script src="https://cdn.tailwindcss.com?plugins=forms"></script>
    //#endif
    //#if (IsBootstrap)
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    //#endif
    //#if (IsPico)
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@picocss/pico@1/css/pico.min.css">
    //#endif
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="//unpkg.com/alpinejs" defer></script>
    <style>
        [x-cloak] {
            display: none !important;
        }
    </style>
</head>
﻿//#if (IsTailwind)
<body class="bg-gray-50">
    @await Html.PartialAsync("_NavMenu")
    <main class="container px-6 max-w-6xl mx-auto py-12">
        @RenderBody()
    </main>
    @await RenderSectionAsync("Scripts", required: false)
</body>
//#endif
﻿//#if (IsPico)
<body>
    @await Html.PartialAsync("_NavMenu")
    <main class="container">
        @RenderBody()
    </main>
    @await RenderSectionAsync("Scripts", required: false)
</body>
//#endif
﻿//#if (IsBootstrap)
<body class="bg-body-tertiary">
    @await Html.PartialAsync("_NavMenu")
    <main>
        @RenderBody()
    </main>
    @await RenderSectionAsync("Scripts", required: false)
</body>
//#endif
</html>

Spark.Templates/working/templates/Spark.Templates.Razor/Pages/Shared/_NavMenu.cshtml
﻿//#if (IsTailwind)
<nav class="container w-full max-w-6xl mx-auto px-6" x-data="{ desktopMenuOpen: false, mobileMenuOpen: false }">
	<div class="flex justify-between items-center">
		<ul>
			<li class="py-4">
				<a href="/">
					@await Html.PartialAsync("_ApplicationLogo")
				</a>
			</li>
		</ul>
		<ul class="flex-wrap items-center w-auto hidden md:flex space-x-4">
			@if (User.Identity != null && User.Identity.IsAuthenticated)
			{
				<div class="relative ml-3">
					<div>
						<button x-on:click="desktopMenuOpen = true" type="button" class="inline-flex items-center rounded-full bg-transparent" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
							<span class="sr-only">Open user menu</span>
							@User.Identity.Name
							<svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6" /></svg>
						</button>
					</div>
					<div x-cloak x-on:click.outside="desktopMenuOpen = false" x-show="desktopMenuOpen" class="absolute right-0 z-50 mt-2 w-48 origin-top-right shadow-2xl bg-white py-1 border border-gray-600" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
						<div>
							<a href="/dashboard" class="block px-4 py-4 text-gray-600 hover:text-black hover:bg-gray-100" role="menuitem">
								Dashboard
							</a>
							<a href="/profile/edit" class="block px-4 py-4 text-gray-600 hover:text-black hover:bg-gray-100" role="menuitem">
								Profile
							</a>
							<a href="/logout" class="block px-4 py-4 text-gray-600 hover:text-black hover:bg-gray-100" role="menuitem">
								Logout
							</a>
							<p class="text-sm py-2 px-4 border-t">@User.Identity.Name</p>
						</div>
					</div>
				</div>
			}
			else
			{
				<li class="px-2 py-4">
					<a href="/login" class="text-lg font-medium text-indigo-600 hover:text-indigo-700">
						Login
					</a>
				</li>
				<li class="px-2 py-4">
					<a href="/register" class="px-3 py-4 text-lg bg-indigo-600 hover:bg-indigo-700 text-white rounded-md font-medium">
						Register
					</a>
				</li>
			}
		</ul>
		<div class="w-auto md:hidden">
			<button x-on:click="mobileMenuOpen = !mobileMenuOpen" class="text-gray-600 hover:text-black hover:bg-gray-100 bg-transparent p-2">
				<svg x-show="!mobileMenuOpen" class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
					<path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
				</svg>
				<svg x-show="mobileMenuOpen" class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
					<path fill-rule="evenodd" d="M5.47 5.47a.75.75 0 011.06 0L12 10.94l5.47-5.47a.75.75 0 111.06 1.06L13.06 12l5.47 5.47a.75.75 0 11-1.06 1.06L12 13.06l-5.47 5.47a.75.75 0 01-1.06-1.06L10.94 12 5.47 6.53a.75.75 0 010-1.06z" clip-rule="evenodd" />
				</svg>
			</button>
		</div>
	</div>
	<div x-cloak x-show="mobileMenuOpen" class="lg:hidden bg-white drop-shadow-lg z-50 mb-12" id="mobile-menu">
		<div class="py-3 space-y-1 px-4 md:px-12">
			@if (User.Identity != null && User.Identity.IsAuthenticated)
			{
				<a href="/dashboard" class="text-gray-600 hover:bg-gray-100 hover:text-black block px-4 py-2 font-medium">
					Dashboard
				</a>
				<a href="/profile/edit" class="text-gray-600 hover:bg-gray-100 hover:text-black block px-4 py-2 font-medium">
					Profile
				</a>
				<a href="/logout" class="text-gray-600 hover:bg-gray-100 hover:text-black block px-4 py-2 font-medium">
					Logout
				</a>
				<p class="text-sm px-4 py-2 border-t">@User.Identity.Name</p>
			}
			else
			{
				<a href="/login" class="text-gray-600 hover:bg-gray-100 hover:text-black block px-4 py-2 font-medium">Login</a>
				<a href="/register" class="text-gray-600 hover:bg-gray-100 hover:text-black block px-4 py-2 font-medium">Register</a>
			}
		</div>
	</div>
</nav>
//#endif
﻿//#if (IsPico)
<nav class="container" x-data="{ desktopMenuOpen: false, mobileMenuOpen: false }">
	<ul>
		<li>
			<a href="/" class="contrast">
				@await Html.PartialAsync("_ApplicationLogo")
			</a>
		</li>
	</ul>
	<ul>
		@if (User.Identity != null && User.Identity.IsAuthenticated)
		{
			<li>
				<details role="list" dir="rtl">
					<summary aria-haspopup="listbox" role="link">Account</summary>
					<ul role="listbox">
						<li><a href="/dashboard">Dashboard</a></li>
						<li><a href="/profile/edit">Profile</a></li>
						<li><a href="/logout">Logout</a></li>
						<li><small>@User.Identity.Name</small></li>
					</ul>
				</details>
			</li>
		}
		else
		{
			<li><a href="/login">Login</a></li>
			<li><a href="/register" role="button">Register</a></li>
		}
	</ul>
</nav>
//#endif
﻿//#if (IsBootstrap)
<nav class="navbar container">
	<div class="container-fluid">
		<a href="/" class="navbar-brand">
			@await Html.PartialAsync("_ApplicationLogo")
		</a>
		@if (User.Identity != null && User.Identity.IsAuthenticated)
		{
			<div class="btn-group dropstart">
				<button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
					Account
				</button>
				<ul class="dropdown-menu">
					<li><a href="/dashboard" class="dropdown-item">Dashboard</a></li>
					<li><a href="/profile/edit" class="dropdown-item">Profile</a></li>
					<li><a href="/logout" class="dropdown-item">Logout</a></li>
					<li><hr class="dropdown-divider"></li>
					<li class=""><small class="p-2">@User.Identity.Name</small></li>
				</ul>
			</div>
		}
		else
		{
			<div class="">
				<a href="/login" class="me-3">Login</a>
				<a href="/register" class="btn btn-primary">Register</a>
			</div>
		}
	</div>
</nav>
//#endif